function recipe(name)
% recipe  Display the installation recipe for a supported library.
%
%   emk.setup.recipe(name)
%
%   Prints the Track classification, installation commands, license, and
%   any important notes for the named library to the MATLAB Command Window.
%
%   Track 1 libraries (installed into Embedded Python via installExtra):
%     "pubchempy"       - PubChem REST API client
%     "mordred"         - 1800+ molecular descriptors
%     "biopython"       - PDB / sequence analysis
%     "torch"           - PyTorch CPU-only (~800 MB; required before torch_geometric/transformers)
%     "torch_geometric" - PyG graph neural networks (requires torch)
%     "transformers"    - HuggingFace Transformers (requires torch)
%     "datasets"        - HuggingFace Datasets (pairs with transformers)
%     "meeko"           - Ligand PDBQT preparation for AutoDock Vina (LGPL-2.1)
%     "vina"            - AutoDock Vina docking engine Python API (Apache-2.0)
%     "pdbfixer"        - PDB structure preparation; auto-installs openmm (MIT)
%     "docking"         - Combined recipe: meeko + vina + pdbfixer pipeline
%
%   Track 2 libraries (require external CPython; use useExternal to connect):
%     "openbabel"   - Chemical format conversion and 3D coordinate generation
%     "mdanalysis"  - Molecular dynamics trajectory analysis
%     "pymol"       - 3D molecular visualization
%
%   Error IDs:
%     emk:setup:recipe:unknownLibrary - unsupported name
%
%   See also: emk.setup.installExtra, emk.setup.useExternal, emk.setup.validate

    arguments
        name (1,1) string
    end

    switch name
        case "pubchempy"
            printTrack1_( ...
                "pubchempy", ...
                "PubChem REST API client -- compound search and property lookup", ...
                "pubchempy", ...
                "MIT", ...
                "Pure Python. No additional system dependencies.");

        case "mordred"
            printTrack1_( ...
                "mordred", ...
                "1800+ molecular descriptors for QSAR model building", ...
                "mordred", ...
                "BSD-3 (mordredcommunity fork)", ...
                "Installs the mordredcommunity package. Requires numpy and scipy.");

        case "biopython"
            printTrack1_( ...
                "biopython", ...
                "PDB / FASTA / GenBank parsing and bioinformatics utilities", ...
                "biopython", ...
                "Biopython License (BSD-like; see https://biopython.org/DIST/LICENSE)", ...
                "Verify the full license text before use in commercial projects.");

        case "meeko"
            printTrack1_( ...
                "meeko", ...
                "Ligand PDBQT preparation for AutoDock Vina docking", ...
                "meeko", ...
                "LGPL-2.1", ...
                ["Python dynamic import does not trigger LGPL copyleft for EasyMolKit (MIT).", ...
                 "See docs/compliance.md CL-7 for full usage rationale."]);

        case "vina"
            printVina_();

        case "pdbfixer"
            printPdbfixer_();

        case "docking"
            printDocking_();

        case "torch"
            printTrack1_( ...
                "torch", ...
                "PyTorch deep learning framework (CPU-only build, ~800 MB)", ...
                "torch --index-url https://download.pytorch.org/whl/cpu", ...
                "BSD-3", ...
                ["CPU-only wheel. GPU/CUDA support is not available in Embedded Python.", ...
                 "Must be installed BEFORE torch_geometric or transformers.", ...
                 "Large download (~800 MB). Ensure stable internet connection."]);

        case "torch_geometric"
            printTrack1_( ...
                "torch_geometric", ...
                "PyTorch Geometric -- graph neural networks for molecules", ...
                "torch_geometric", ...
                "MIT", ...
                ["Requires torch to be installed first: emk.setup.installExtra(""torch"")", ...
                 "Also installs companion packages: torch_scatter, torch_sparse, torch_cluster.", ...
                 "Version URLs are auto-detected from the installed torch version."]);

        case "transformers"
            printTrack1_( ...
                "transformers", ...
                "HuggingFace Transformers -- pre-trained language and chemistry models", ...
                "transformers", ...
                "Apache-2.0", ...
                ["Requires torch to be installed first: emk.setup.installExtra(""torch"")", ...
                 "Compatible with MIT license. No additional restrictions."]);

        case "datasets"
            printTrack1_( ...
                "datasets", ...
                "HuggingFace Datasets -- fast dataset loading and processing", ...
                "datasets", ...
                "Apache-2.0", ...
                ["Commonly used together with transformers for model training and evaluation.", ...
                 "Compatible with MIT license. No additional restrictions."]);

        case "openbabel"
            printTrack2_( ...
                "openbabel", ...
                "Chemical format conversion (110+ formats) and 3D coordinate generation", ...
                ["REQUIREMENT: Python 3.8 or earlier on Windows.", ...
                 "  The official Windows installer (Open Babel 3.1.1, released May 2020)", ...
                 "  was compiled against Python <= 3.8.  Python 3.9+ is NOT supported.", ...
                 "  If you only have Python 3.9+, consider RDKit (already in Track 1)", ...
                 "  for format conversion, or use WSL/Linux where apt-get install works.", ...
                 "", ...
                 "IMPORTANT: Do NOT run 'pip install openbabel'.", ...
                 "           pip tries to build from source (needs SWIG + C++ headers).", ...
                 "           The MSI installer places Python bindings directly.", ...
                 "", ...
                 "Step 1 -- Install Python 3.8 from python.org:", ...
                 "         https://www.python.org/downloads/release/python-3817/", ...
                 "", ...
                 "Step 2 -- Download the Windows installer (with Python bindings):", ...
                 "         https://github.com/openbabel/openbabel/releases/tag/openbabel-3-1-1", ...
                 "         Choose: OpenBabel-3.1.1-x64.exe (36.9 MB)", ...
                 "         During installation: check the 'Python bindings' checkbox.", ...
                 "         When asked, select Python 3.8 (e.g., C:\Python38).", ...
                 "", ...
                 "Step 3 -- Verify the installation from cmd/PowerShell:", ...
                 "         C:\Python38\python.exe -c ""import openbabel; print('OK')""", ...
                 "", ...
                 "Step 4 -- Connect EasyMolKit to that Python:", ...
                 "         emk.setup.useExternal(""C:\\Python38\\python.exe"")", ...
                 "         NOTE: No venv needed. Point directly to the Python the MSI installed into.", ...
                 "", ...
                 "Step 5 -- Validate:", ...
                 "         T = emk.setup.validate(Libraries=""openbabel"")"], ...
                "GPLv2", ...
                ["WARNING: Open Babel is licensed under GPLv2.", ...
                 "EasyMolKit (MIT) is not affected, but your scripts", ...
                 "that use Open Babel may be subject to GPLv2 terms.", ...
                 "For automated installation (pip-only), consider:", ...
                 "  emk.setup.installTrack2(""mdanalysis"")  % or ""pymol"""]);

        case "mdanalysis"
            printTrack2_( ...
                "mdanalysis", ...
                "Molecular dynamics trajectory analysis (GROMACS, AMBER, NAMD, ...)", ...
                ["Step 1 -- Create a CPython 3.10+ virtual environment:", ...
                 "         python -m venv C:\envs\mdenv", ...
                 "Step 2 -- Install MDAnalysis into it:", ...
                 "         C:\envs\mdenv\Scripts\pip install MDAnalysis", ...
                 "Step 3 -- Connect EasyMolKit:", ...
                 "         emk.setup.useExternal(""C:\\envs\\mdenv\\python.exe"")", ...
                 "Step 4 -- Validate:", ...
                 "         T = emk.setup.validate(Libraries=""mdanalysis"")"], ...
                "GPLv2+", ...
                ["WARNING: GPL library.", ...
                 "EasyMolKit (MIT) is unaffected, but your scripts that", ...
                 "use MDAnalysis may be subject to GPLv2+ terms."]);

        case "pymol"
            printTrack2_( ...
                "pymol", ...
                "3D molecular visualization -- PyMOL Open-Source edition", ...
                ["RECOMMENDED: Use installTrack2 for automatic setup:", ...
                 "         emk.setup.installTrack2(""pymol"", BasePython=""C:\\Python310\\python.exe"")", ...
                 "", ...
                 "MANUAL STEPS (if installTrack2 is not used):", ...
                 "  NOTE: pymol-open-source on PyPI causes DLL load failures on Windows.", ...
                 "        Use Gohlke prebuilt wheels which bundle all native DLLs:", ...
                 "        https://github.com/cgohlke/pymol-open-source-wheels/releases", ...
                 "", ...
                 "Step 1 -- Create a CPython 3.10+ virtual environment:", ...
                 "         python -m venv C:\envs\pymolenv", ...
                 "Step 2 -- Install PyMOL from Gohlke prebuilt wheel (cp310 example):", ...
                 "         C:\envs\pymolenv\Scripts\pip install ^", ...
                 "           https://github.com/cgohlke/pymol-open-source-wheels/releases/download/v2025.2.2/pymol-3.1.0-cp310-cp310-win_amd64.whl", ...
                 "         (For cp311/cp312/cp313 see the releases page above)", ...
                 "Step 3 -- Connect EasyMolKit:", ...
                 "         emk.setup.useExternal(""C:\\envs\\pymolenv\\Scripts\\python.exe"")", ...
                 "Step 4 -- Validate:", ...
                 "         T = emk.setup.validate(Libraries=""pymol"")"], ...
                "Python-2.0 (PSF) / BSD hybrid", ...
                ["Confirm license at:", ...
                 "  https://github.com/schrodinger/pymol-open-source/blob/master/LICENSE"]);

        otherwise
            error("emk:setup:recipe:unknownLibrary", ...
                "Unknown library: '%s'.\n" + ...
                "Supported: pubchempy, mordred, biopython, " + ...
                "torch, torch_geometric, transformers, datasets, " + ...
                "meeko, vina, pdbfixer, docking, " + ...
                "openbabel, mdanalysis, pymol.", name);
    end
end

% =========================================================================
% Private helpers
% =========================================================================

function printDocking_()
% Display combined Track 1 docking pipeline recipe (meeko + vina + pdbfixer).
    sep = repmat("=", 1, 62);
    logInfo("%s", sep);
    logInfo("Recipe: docking pipeline  (Track 1 -- Embedded Python)");
    logInfo("%s", sep);
    logInfo("Description  : AutoDock Vina docking pipeline");
    logInfo("               Components: meeko + vina + pdbfixer (+ openmm)");
    if emk.util.isOnline()
        logInfo("Install via  : !~/.local/bin/pip install --user meeko vina pdbfixer");
        logInfo("               (MATLAB Online: installExtra() is not available)", "");
    else
        logInfo("Install via  : emk.setup.installExtra(""meeko"")");
        logInfo("               emk.setup.installExtra(""pdbfixer"")");
        logInfo("               (pdbfixer auto-installs openmm >= 8.2 as dependency)");
        logInfo("               --- vina: No Windows wheel. Use standalone binary ---");
        logInfo("               New-Item -ItemType Directory -Force ""python_env_t2\\vina""");
        logInfo("               Invoke-WebRequest ``");
        logInfo("                 -Uri ""https://github.com/ccsb-scripps/AutoDock-Vina/releases/download/v1.2.7/vina_1.2.7_win.exe"" ``");
        logInfo("                 -OutFile ""python_env_t2\\vina\\vina.exe""");
        logInfo("               For full details: emk.setup.recipe(""vina"")");
    end
    logInfo("License      : meeko: LGPL-2.1  /  vina: Apache-2.0");
    logInfo("               pdbfixer: MIT  /  openmm: MIT + LGPL");
    logInfo("Sample data  : data/docking/sample_ligand.sdf");
    logInfo("               data/docking/sample_protein.pdb");
    logInfo("Notes        : meeko LGPL dynamic import is safe for MIT projects.");
    logInfo("               openmm LGPL dynamic import is safe for MIT projects.");
    logInfo("               See docs/compliance.md for full usage rationale.");
    logInfo("%s", sep);
end

% -------------------------------------------------------------------------
function printTrack1_(name, description, installName, license_, notes)
% Display a Track 1 (Embedded Python / installExtra) recipe.
% On MATLAB Online, show the pip --user alternative instead.
    sep = repmat("=", 1, 62);
    logInfo("%s", sep);
    logInfo("Recipe: %s  (Track 1 -- Embedded Python)", name);
    logInfo("%s", sep);
    logInfo("Description  : %s", description);
    if emk.util.isOnline()
        logInfo("Install via  : !~/.local/bin/pip install --user %s", installName);
        logInfo("               (MATLAB Online: installExtra() is not available)", "");
    else
        logInfo("Install via  : emk.setup.installExtra(""%s"")", installName);
    end
    logInfo("License      : %s", license_);
    logInfo("Notes        : %s", notes);
    logInfo("%s", sep);
end

% -------------------------------------------------------------------------
function printTrack2_(name, description, steps, license_, notes)
% Display a Track 2 (external CPython) recipe.
% On MATLAB Online, Track 2 libraries cannot be installed (persistent venv
% creation is not supported).  Show a brief unavailability notice instead
% of Windows-specific paths that are meaningless in the Online environment.
    sep = repmat("=", 1, 62);
    logInfo("%s", sep);
    logInfo("Recipe: %s  (Track 2 -- External Python required)", name);
    logInfo("%s", sep);
    logInfo("Description  : %s", description);
    if emk.util.isOnline()
        logInfo("Availability : NOT available on MATLAB Online.", "");
        logInfo("               Track 2 libraries require a Windows Desktop", "");
        logInfo("               environment with a persistent CPython + venv.", "");
    else
        logInfo("Installation :");
        for i = 1:numel(steps)
            logInfo("  %s", steps(i));
        end
    end
    logInfo("License      : %s", license_);
    for i = 1:numel(notes)
        if i == 1
            logInfo("Notes        : %s", notes(i));
        else
            logInfo("               %s", notes(i));
        end
    end
    logInfo("%s", sep);
end

% -------------------------------------------------------------------------
function printVina_()
% Display the AutoDock Vina recipe.
% On Windows, the PyPI vina package has no pre-built wheel, so show the
% standalone binary installation steps (Track 2 style).
% On Linux/macOS/WSL2, installExtra() is available.
    sep = repmat("=", 1, 62);
    logInfo("%s", sep);
    if emk.util.isOnline()
        logInfo("Recipe: vina  (MATLAB Online -- pip --user)");
        logInfo("%s", sep);
        logInfo("Description  : AutoDock Vina molecular docking engine Python API");
        logInfo("Install via  : !~/.local/bin/pip install --user vina");
        logInfo("License      : Apache-2.0");
    elseif ispc()
        logInfo("Recipe: vina  (Windows -- Standalone Binary, Track 2 style)");
        logInfo("%s", sep);
        logInfo("Description  : AutoDock Vina molecular docking engine");
        logInfo("               Note: PyPI has NO Windows wheel -- standalone exe required.");
        logInfo("Installation :");
        logInfo("  Step 1 -- Create the binary folder (run in PowerShell):");
        logInfo("            New-Item -ItemType Directory -Force ""python_env_t2\\vina""");
        logInfo("  ");
        logInfo("  Step 2 -- Download the Windows binary (~16 MB):");
        logInfo("            Invoke-WebRequest ``");
        logInfo("              -Uri ""https://github.com/ccsb-scripps/AutoDock-Vina/releases/download/v1.2.7/vina_1.2.7_win.exe"" ``");
        logInfo("              -OutFile ""python_env_t2\\vina\\vina.exe""");
        logInfo("            (Or download manually from the Releases page and save as vina.exe)");
        logInfo("            https://github.com/ccsb-scripps/AutoDock-Vina/releases");
        logInfo("  ");
        logInfo("  Step 3 -- Verify from PowerShell:");
        logInfo("            .\\python_env_t2\\vina\\vina.exe --help");
        logInfo("  ");
        logInfo("  Step 4 -- Call from MATLAB:");
        logInfo("            vinaExe = fullfile(pwd, ""python_env_t2"", ""vina"", ""vina.exe"");");
        logInfo("            system(['""' vinaExe '"" --help'])");
        logInfo("License      : Apache-2.0");
        logInfo("Notes        : No Python venv needed. The standalone exe is equivalent");
        logInfo("               to the pip ""vina"" package on Linux/macOS.");
        logInfo("               For pip-based usage, run on Linux/macOS/WSL2 where");
        logInfo("               emk.setup.installExtra(""vina"") works normally.");
    else
        % Linux / macOS -- installExtra is available
        logInfo("Recipe: vina  (Track 1 -- Embedded Python)");
        logInfo("%s", sep);
        logInfo("Description  : AutoDock Vina molecular docking engine Python API");
        logInfo("Install via  : emk.setup.installExtra(""vina"")");
        logInfo("License      : Apache-2.0");
        logInfo("Notes        : Compatible with MIT license. No additional restrictions.");
    end
    logInfo("%s", sep);
end

% -------------------------------------------------------------------------
function printPdbfixer_()
% Display the pdbfixer recipe with platform-specific instructions.
% Windows Desktop: openmm .pyd is blocked by Smart App Control -- direct to Online.
% MATLAB Online (Linux): pip --user works; show both flag and manual paths.
% Other platforms: standard Track 1 recipe.
    sep = repmat("=", 1, 62);
    logInfo("%s", sep);
    if emk.util.isOnline()
        logInfo("Recipe: pdbfixer  (MATLAB Online -- pip --user)");
        logInfo("%s", sep);
        logInfo("Description  : PDB structure preparation -- missing residues,");
        logInfo("               hydrogens, protonation state correction.");
        logInfo("               Auto-installs openmm >= 8.2 (~70 MB) as dependency.");
        logInfo("Install via  : Option A (recommended) -- via main_emk.m:");
        logInfo("               1. Open main_emk.m");
        logInfo("               2. In Section 0a, set:");
        logInfo("                    cfg.optionalLibraries.pdbfixer = true");
        logInfo("               3. Run Section 0b");
        logInfo("               Option B -- manual pip:");
        logInfo("               !~/.local/bin/pip install --user pdbfixer");
        logInfo("License      : pdbfixer: MIT  /  openmm: MIT + LGPL");
        logInfo("Notes        : openmm LGPL dynamic import is safe for MIT projects.");
    elseif ispc()
        logInfo("Recipe: pdbfixer  (Windows Desktop -- NOT SUPPORTED)");
        logInfo("%s", sep);
        logInfo("Description  : PDB structure preparation (missing residues, hydrogens).");
        logInfo("Status       : BLOCKED -- pdbfixer requires openmm, whose native .pyd");
        logInfo("               extension is blocked by Windows Smart App Control (SAC).");
        logInfo("               This is a Windows security policy and cannot be");
        logInfo("               bypassed in code.");
        logInfo("Workaround   : Use MATLAB Online (Linux) instead:");
        logInfo("               1. Open main_emk.m");
        logInfo("               2. In Section 0a, set:");
        logInfo("                    cfg.optionalLibraries.pdbfixer = true");
        logInfo("               3. Run Section 0b");
        logInfo("               For the full docking pipeline, also enable:");
        logInfo("                    cfg.optionalLibraries.meeko = true");
        logInfo("                    cfg.optionalLibraries.vina  = true");
        logInfo("License      : pdbfixer: MIT  /  openmm: MIT + LGPL");
    else
        logInfo("Recipe: pdbfixer  (Track 1 -- Embedded Python)");
        logInfo("%s", sep);
        logInfo("Description  : PDB structure preparation (missing residues, hydrogens).");
        logInfo("               Auto-installs openmm >= 8.2 (~70 MB) as dependency.");
        logInfo("Install via  : emk.setup.installExtra(""pdbfixer"")");
        logInfo("License      : pdbfixer: MIT  /  openmm: MIT + LGPL");
        logInfo("Notes        : openmm LGPL dynamic import is safe for MIT projects.");
    end
    logInfo("%s", sep);
end
